services:
  # PostgreSQL Database
  - type: pserv
    name: poke-guessr-db
    env: docker
    plan: free
    databaseName: pokemon_guessr
    user: pokemon_user

  # Backend API
  - type: web
    name: poke-guessr-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm ci
      cd data
      pip install -r requirements.txt
      chmod +x setup_db.sh
      ./setup_db.sh
      cd ../
      npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: poke-guessr-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: poke-guessr-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://poke-guessr.onrender.com
